version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - postgres_admin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres
volumes:
  db_data:
  postgres_admin:
networks:
  postgres:
    driver: bridge
